PROJECT_DEPS :=

mcEigen:PRIVATE_BUILD_DIR :=$(BUILDDIR)/library/mcEigen
mcEigen:PRIVATE_MK_FILE := $(abspath $(lastword $(MAKEFILE_LIST)))
mcEigen:PRIVATE_MK_PATH := $(patsubst %/, %, $(dir $(PRIVATE_MK_FILE)))
mcEigen: $(PROJECT_DEPS)
	cmake   -DEIGEN_TEST_MACA=ON               \
		-DBUILD_TESTING_GPU_ONLY=ON			\
		-DMACA_CLANG_PATH=$(MACA_CLANG_PATH) 		\
		-DMACA_PATH=$(MACA_PATH)			\
		-DCMAKE_CXX_COMPILER=${MACA_CLANG_PATH}/mxcc	\
		-DCMAKE_BUILD_TYPE=$(BUILD_TYPE)  		\
		-DBUILD_NUMBER=$(BUILD_NUMBER)			\
		-B $(PRIVATE_BUILD_DIR)           		\
		-S $(PRIVATE_MK_PATH)             		\
		-DCMAKE_INSTALL_PREFIX=${BUILDROOT} \
		-DCMAKE_PACKAGE_DIR=$(PRIVATE_BUILD_DIR) -DPACKAGE_ARCH=$(PACK_ARCH) -DPACKAGE_EXT=$(PACK_EXT) \
		-DCMAKE_TARGET_ARCH=${ARCH} \
		-DMACA_VERSION=${MACA_VERSION} \
		-DDISTRO_CODE=${DISTRO_CODE} \
		-DDEB_PACKAGE_ARCH=$(DEB_PACK_ARCH) -DRPM_PACKAGE_ARCH=$(RPM_PACK_ARCH) -DPACKAGE_LOCATION=$(PACK_LOCATION) \
		-DPACKAGE_GENERATOR="$(PACKAGE_GENERATOR)"
	$(MAKE) buildtests -j$(NUM_JOB) -C $(PRIVATE_BUILD_DIR)
	$(MAKE) install -C $(PRIVATE_BUILD_DIR)

mcEigen_package: PRIVATE_BUILD_DIR := $(BUILDDIR)/library/mcEigen
mcEigen_package:
	${MAKE} package -C $(PRIVATE_BUILD_DIR)

mcEigen-clean: PRIVATE_BUILD_DIR := $(BUILDDIR)/library/mcEigen
mcEigen-clean:
	rm -rf $(PRIVATE_BUILD_DIR)
