# manually modify minimum supported versions when the latest versions are
# incompatible with some of the following versions
set(PADDLE_MINIMUM_VERSION_MAJOR 2)
set(PADDLE_MINIMUM_VERSION_MINOR 5)
set(PADDLE_MINIMUM_VERSION_PATCH 1)
set(PADDLE_MINIMUM_VERSION_TYPE)
set(PADDLE_MINIMUM_VERSION_TYPENO 0)

set(RUNTIME_MINIMUM_VERSION_MAJOR 0)
set(RUNTIME_MINIMUM_VERSION_MINOR 14)
set(RUNTIME_MINIMUM_VERSION_PATCH 0)
set(RUNTIME_MINIMUM_VERSION_TYPE)
set(RUNTIME_MINIMUM_VERSION_TYPENO 0)

set(DRIVER_MINIMUM_VERSION_MAJOR 0)
set(DRIVER_MINIMUM_VERSION_MINOR 16)
set(DRIVER_MINIMUM_VERSION_PATCH 0)
set(DRIVER_MINIMUM_VERSION_TYPE b)
set(DRIVER_MINIMUM_VERSION_TYPENO 1)

set(TECO_DNN_MINIMUM_VERSION_MAJOR 1)
set(TECO_DNN_MINIMUM_VERSION_MINOR 11)
set(TECO_DNN_MINIMUM_VERSION_PATCH 0)
set(TECO_DNN_MINIMUM_VERSION_TYPE)
set(TECO_DNN_MINIMUM_VERSION_TYPENO 0)

set(TECO_BLAS_MINIMUM_VERSION_MAJOR 1)
set(TECO_BLAS_MINIMUM_VERSION_MINOR 11)
set(TECO_BLAS_MINIMUM_VERSION_PATCH 0)
set(TECO_BLAS_MINIMUM_VERSION_TYPE)
set(TECO_BLAS_MINIMUM_VERSION_TYPENO 0)

set(TECO_CUSTOM_MINIMUM_VERSION_MAJOR 1)
set(TECO_CUSTOM_MINIMUM_VERSION_MINOR 12)
set(TECO_CUSTOM_MINIMUM_VERSION_PATCH 0)
set(TECO_CUSTOM_MINIMUM_VERSION_TYPE b)
set(TECO_CUSTOM_MINIMUM_VERSION_TYPENO 0)

set(TCCL_MINIMUM_VERSION_MAJOR 1)
set(TCCL_MINIMUM_VERSION_MINOR 10)
set(TCCL_MINIMUM_VERSION_PATCH 0)
set(TCCL_MINIMUM_VERSION_TYPE)
set(TCCL_MINIMUM_VERSION_TYPENO 0)

set(SDPTI_MINIMUM_VERSION_MAJOR 0)
set(SDPTI_MINIMUM_VERSION_MINOR 2)
set(SDPTI_MINIMUM_VERSION_PATCH 0)
set(SDPTI_MINIMUM_VERSION_TYPE b)
set(SDPTI_MINIMUM_VERSION_TYPENO 0)
