name: PR-CI-HPU

on:
  workflow_call:
    inputs:
      workflow-name:
        type: string
        required: false
      clone_dir:
        type: string
        required: false
        default: 'PaddlecustomDevice'
      is_pr:
        type: string
        required: false
        default: 'true'

jobs:
  check-bypass:
    name: Check bypass
    if: ${{ inputs.can-skip != 'true' }}
    uses: ./.github/workflows/check-bypass.yml
    with:
      workflow-name: 'hpu'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  PR-CI-HPU:
    name: PR-CI-HPU
    needs: check-bypass
    if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
    runs-on:
      group: HPU
    env:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      BRANCH: develop
      TASK: paddle-CI-${{ github.event.pull_request.number }}-hpu
      no_proxy: "bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn"

    steps:
      - name: Check docker image and run container
        env:
          GIT_PR_ID: ${{ github.event.pull_request.number || '0' }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          cache_dir: /root/.cache
          ccache_dir: /root/.ccache
          docker_image: ccr-2vdh3abv-pub.cnc.bj.baidubce.com/device/paddle-hpu:ci
        run: |
          container_name=${TASK}-$(date +%Y%m%d-%H%M%S)
          echo "container_name=${container_name}" >> ${{ github.env }}
          docker run --shm-size=128G \
            -d -t --name ${container_name} \
            --privileged --network=host \
            -e PR_ID \
            -e COMMIT_ID \
            -e BRANCH \
            -e no_proxy \
            -v ${cache_dir}:/root/.cache \
            -v ${ccache_dir}:/root/.ccache \
            -v ${{ github.workspace }}/../../..:${{ github.workspace }}/../../.. \
            -v ${{ github.workspace }}:/workspace -w /workspace \
            ${docker_image} /bin/bash

      - name: Download Code
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -c '
          rm -rf * .[^.]*
          source ${{ github.workspace }}/../../../proxy
          set -x
          wget -q --tries=5 --no-proxy https://paddle-github-action.bj.bcebos.com/PaddleCustomDevice/PR/${PR_ID}/${COMMIT_ID}/PaddleCustomDevice.tar.gz --no-check-certificate
          echo "Extracting PaddleCustomDevice.tar.gz"
          tar -xf PaddleCustomDevice.tar.gz
          cd PaddleCustomDevice
          git config --global --add safe.directory "*"
          git remote add upstream https://github.com/PaddlePaddle/PaddleCustomDevice.git
          git merge ${BRANCH} --no-edit
          git --no-pager log --pretty=oneline -5'

      - name: RUN HPU
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -c '
          cd PaddleCustomDevice
          # !!!!! SKIP IF NO HPU CHANGE !!!!
          echo "=========== Checking PR Changes If HPU FULL CI Needed ==========="
          change_numbers=$(git diff --name-only remotes/origin/${BRANCH} | wc -l)
          change_backend=$(git diff --name-only remotes/origin/${BRANCH} | grep "backends/"| wc -l)
          change_hpu_only=$(git diff --name-only remotes/origin/${BRANCH} | grep "backends/intel_hpu"| wc -l)
          git diff --name-only remotes/origin/${BRANCH}
          if [ $change_numbers -ne $change_backend ]; then
            echo "Common file changed, continue to run HPU FULL CI test ..."
          elif [ $change_hpu_only -eq 0 ] ; then
            echo "NO HPU backend changes found, skip HPU FULL CI ...."
            exit 0
          fi
          mkdir -p /workspace/PaddleCustomDevice/backends/intel_hpu/build/
          export GC_KERNEL_PATH=/workspace/PaddleCustomDevice/backends/intel_hpu/build/libcustom_tpc_perf_lib.so:/usr/lib/habanalabs/libtpc_kernels.so
          export PADDLE_VERSION=0.0.0
          cd /workspace
          bash /workspace/PaddleCustomDevice/backends/intel_hpu/tools/pr_hpu_ci.sh'

      - name: Terminate and delete the container
        if: always()
        run: |
          docker exec -t ${{ env.container_name }} /bin/bash -c '
          rm -rf * .[^.]*
          '
          docker stop ${container_name}
          docker rm ${container_name}
