name: PR-CI-METAX


on:
  workflow_call:
    inputs:
      workflow-name:
        type: string
        required: false
      clone_dir:
        type: string
        required: false
        default: 'PaddlecustomDevice'
      is_pr:
        type: string
        required: false
        default: 'true'


defaults:
  run:
    shell: bash


jobs:

  check-bypass:
    name: Check bypass
    if: ${{ inputs.can-skip != 'true' }}
    uses: ./.github/workflows/check-bypass.yml
    with:
      workflow-name: 'metax'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  PR-CI-METAX:
    name: PR-CI-METAX
    needs: check-bypass
    if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
    runs-on: paddle-metax-runner-set
    env:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      BRANCH: develop

    steps:
      - name: Download Code
        run: |
          set -x
          wget -q --tries=5 --no-proxy https://paddle-github-action.bj.bcebos.com/PaddleCustomDevice/PR/${PR_ID}/${COMMIT_ID}/PaddleCustomDevice.tar.gz --no-check-certificate
          echo "Extracting PaddleCustomDevice.tar.gz"
          tar -xf PaddleCustomDevice.tar.gz
          cd PaddleCustomDevice
          git config --global --add safe.directory "*"
          git remote add upstream https://github.com/PaddlePaddle/PaddleCustomDevice.git
          git merge ${BRANCH} --no-edit
          git --no-pager log --pretty=oneline -5


      - name: RUN METAX-GPU
        id: run-metax
        if: steps.check-bypass.outputs.can-skip != 'true'
        run: |
          cd PaddleCustomDevice
          # !!!!! SKIP IF NO METAX CHANGE !!!!
          echo "=========== Checking PR Changes If METAX FULL CI Needed ==========="
          change_numbers=$(git diff --name-only remotes/origin/${BRANCH} | wc -l)
          change_backend=$(git diff --name-only remotes/origin/${BRANCH} | grep "backends/"| wc -l)
          change_metax_only=$(git diff --name-only remotes/origin/${BRANCH} | grep "backends/metax_gpu"| wc -l)
          git --no-pager diff --name-only remotes/origin/${BRANCH}

          if [ $change_numbers -ne $change_backend ]; then
            echo "Common file changed, continue to run METAX FULL CI test ..."
          elif [ $change_metax_only -eq 0 ] ; then
            echo "NO METAX  backend changes found, skip MLU FULL CI ...."
            exit 0
          fi

      - name: compile
        run: |
          cd PaddleCustomDevice/backends/metax_gpu
          bash build.sh

      - name: run test
        run: |
          cd PaddleCustomDevice/backends/metax_gpu/tests
          bash run_test.sh -j 8 -b "default"

      - name: push whl
        env:
          PR_ID: ${{ github.event.pull_request.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}
        run: |
          pip install bce-python-sdk==0.8.74
          export AK=paddle
          export SK=paddle
          if [ ! -f "BosClient.py}" ]; then
            wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_retry.tar.gz --no-check-certificate
            tar xf bos_retry.tar.gz
          fi
          cp PaddleCustomDevice/backends/metax_gpu/build/dist/paddle_metax_gpu*.whl .
          python BosClient.py paddle_metax_gpu*.whl paddle-github-action/PaddleCustomDevice/metax_gpu/${PR_ID}/${COMMIT_ID}
