name: paddle metax gpu test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches: [develop, release/**]
    paths:
      - "**"
      - "Paddle/**"
      - "!backends/**"
      - "backends/metax_gpu/**"

permissions: read-all

defaults:
  run:
    shell: bash

jobs:
  metax-gpu-test:
    runs-on: paddle-metax-runner-set
    # runs-on: debug-paddle-runner-set
    steps:
      - name: Checkout repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone \
            --reference-if-able /home/runner/PaddleCustomDevice \
            --depth=1 \
            --shallow-submodules \
            --jobs=8 \
            --branch ${{ github.base_ref || github.ref_name}} \
            --recurse-submodules \
            https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            git fetch origin pull/${{ github.event.pull_request.number }}/head:pull/${{ github.event.pull_request.number }}/head
            git checkout pull/${{ github.event.pull_request.number }}/head

            git submodule update --init --recursive
          fi


      - name: compile
        run: |
          cd backends/metax_gpu
          bash build.sh

      - name: run test
        run: |
          cd backends/metax_gpu/tests
          bash run_test.sh -j 16
