name: Update Paddle Submodule NightlyAdd commentMore actions

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-submodule-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Paddle Submodule
        run: |
          set -x
          echo "BRANCH_NAME=update-paddle-submodule-$(date +'%Y%m%d')" >> $GITHUB_ENV
          git config --global user.name "tianshuo78520a"
          git config --global user.email "tianshuo78520a@users.noreply.github.com"
          cd Paddle
          git reset --hard HEAD
          git clean -fd
          cd ..
          git submodule update --remote --init
          git add -A
          git commit -m "Update submodule" || echo "No changes to commit"
          git status
          echo "check submodule status"
          git submodule status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          title: "Nightly Update: Paddle Submodule"
          body: "Automated PR to update Paddle submodule to the latest commit."
          commit-message: "Update Paddle submodule"
          base: develop
          labels: "automated,submodule"
